version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

mkdocs:
  configuration_file: mkdocs.yml

python:
  install:
    - requirements: agentfly/requirements.txt
    - requirements: docs/requirements-docs.txt
