version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: src/agentfly/requirements.txt
    - requirements: docs/requirements-docs.txt
