# .readthedocs.yaml (identical structure to veRL’s)           #:contentReference[oaicite:2]{index=2}
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: agents/requirements.txt
    - requirements: verl/requirements.txt
    - requirements: docs/requirements-docs.txt
